### ISSUE TITLE
html bot

### ISSUE THREAD

**Issue by bsimjoo** [maubot/plugin-wishlist#25]
I cannot send a table or other available html codes but bots can! I need a bot that convert this:
```html
<table>
    <tr>
        <th>header 1</th>
        <th>header 2</th>
    </tr>
    <tr>
        <td>blabla</td>
        <td>foobar</td>
    </tr>
</table>
```
to this:
<table>
    <tr>
        <th>header 1</th>
        <th>header 2</th>
    </tr>
    <tr>
        <td>blabla</td>
        <td>foobar</td>
    </tr>
</table>

**Comment by ghost** [comment]
Assuming you're using Element, try `/html ` before your message.

**Comment by bsimjoo** [comment]
Oh yes it works, I'm sorry. I didn't know it. thanks
